-- 코드를 입력하세요
/*SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO

WHERE REST_ID IN (SELECT MAX(FAVORITES) AS FAVORITES
                 FROM REST_INFO
                 GROUP BY FOOD_TYPE)
                 
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE*/
SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES 
FROM REST_INFO

WHERE FAVORITES IN (SELECT MAX(FAVORITES)
                    FROM REST_INFO
                    GROUP BY FOOD_TYPE)

GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC