SELECT I.FLAVOR
FROM FIRST_HALF F JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
WHERE I.INGREDIENT_TYPE = "fruit_based"
GROUP BY F.FLAVOR 
HAVING SUM(F.TOTAL_ORDER) > 3000
ORDER BY SUM(F.TOTAL_ORDER) DESC