/* 처음에 SUM(B.AMOUNT)로만 해서 총 매출이 아니라 총 수량만 구해짐. 문제 잘 보고 주의하기 
+WHERE B.PRODUCE_DATE LIKE '2022-05%' 가 더 간단할거같음
*/

SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE*B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE TO_CHAR(B.PRODUCE_DATE, 'YYYYMM') = '202205'
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;


