-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A JOIN PATIENT P ON P.PT_NO = A.PT_NO JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE A.MCDP_CD = 'CS' AND EXTRACT(YEAR FROM A.APNT_YMD) = 2022 AND  EXTRACT(MONTH FROM A.APNT_YMD) = 4 AND EXTRACT(DAY FROM A.APNT_YMD) = 13 AND APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD