SELECT CONCAT('/home/grep/src/', UFILE.BOARD_ID, '/', UFILE.FILE_ID, UFILE.FILE_NAME, UFILE.FILE_EXT) AS FILEPATH
/*concat() : 여러 문자열 하나로 합쳐주는 역할 concat(str1, str2...) 처럼 concat func에 여러개의 str 쉼표 단위로 추가*/
FROM USED_GOODS_FILE AS UFILE JOIN USED_GOODS_BOARD as UBOARD
ON UFILE.BOARD_ID = UBOARD.BOARD_ID
WHERE UBOARD.VIEWS = 
    (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)

ORDER BY FILEPATH DESC