SELECT a.APNT_NO, p.PT_NAME, a.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM PATIENT p, DOCTOR d, APPOINTMENT a
WHERE (a.PT_NO = p.PT_NO) 
    AND (a.MDDR_ID = d.DR_ID)
    AND (DATE_FORMAT(a.APNT_YMD, '%Y-%m-%d') = '2022-04-13')
    AND (a.APNT_CNCL_YN = 'N')
ORDER BY a.APNT_YMD
