/*  '판매량의 총합'이므로 SUM을 써야됨... 무지성 COUNT금지...*/

SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A
JOIN BOOK_SALES B 
ON A.BOOK_ID=B.BOOK_ID
WHERE TO_CHAR(B.SALES_DATE,'YYYYMM')='202201'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY
