--https://school.programmers.co.kr/learn/courses/30/lessons/59411

SELECT C.ANIMAL_ID, C.NAME
FROM (
    SELECT A.ANIMAL_ID, A.NAME, A.DATETIME, B.DATETIME, TO_DATE(B.DATETIME)-TO_DATE(A.DATETIME) AS DIFF
    FROM ANIMAL_INS A JOIN ANIMAL_OUTS B ON A.ANIMAL_ID=B.ANIMAL_ID
    WHERE B.DATETIME IS NOT NULL
    ORDER BY DIFF DESC
)C
WHERE ROWNUM<3